---
# tasks file for docker-engine

- name: Check distribution & version
  fail:
    msg: Distribution "{{ ansible_distribution }}" is not supported by this role
  when: ansible_distribution != 'Ubuntu' or ansible_distribution_version|version_compare(14.04, '<')

- name: Install 'software-properties-common'
  apt:
    name: software-properties-common
    state: latest
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time }}"

- name: Add updated python repository 
  apt_repository:
    repo: "{{ python_update_repo }}"
    state: present
    update_cache: yes

- name: Upgrade python2.7
  apt:
    name: python2.7
    state: latest

- name: Install 'linux-image-extra-{{ ansible_kernel }}'
  apt:
    name: "linux-image-extra-{{ ansible_kernel }}"
    state: latest

- name: Install 'linux-image-extra-virtual'
  apt:
    name: linux-image-extra-virtual
    state: latest

- name: Install 'apt-transport-https'
  apt:
    name: apt-transport-https
    state: latest

- name: Install 'ca-certficates'
  apt:
    name: ca-certificates
    state: latest

- name: Install 'curl'
  apt:
    name: curl
    state: latest

- name: Install Docker repository key
  apt_key:
    id: "{{ docker_gpg_key_id }}"
    url: "{{ docker_gpg_key_url }}"
    state: present

- name: Add Docker repository
  apt_repository:
    repo: "{{ docker_apt_repo }}"
    update_cache: yes
    state: present

- name: Install 'docker-ce'
  apt:
    name: docker-ce
    state: latest

- name: Create Docker group
  group:
    name: docker
    state: present

- name: Start Docker on boot
  service:
    name: docker
    enabled: yes
    state: started

- name: Install 'nfs-common'
  apt:
    name: nfs-common
    state: latest

- name: Check service docker-volume-netshare
  shell: dpkg-query -l 'docker-volume-netshare'
  ignore_errors: true
  register: is_docker_volume_netshare

- name: Download ContainX/docker-volume-netshare
  get_url:
    url: https://github.com/ContainX/docker-volume-netshare/releases/download/v0.32/docker-volume-netshare_0.32_amd64.deb
    dest: /tmp/docker-volume-netshare
  when: is_docker_volume_netshare|failed

- name: Install 'docker-volume-netshare'
  apt:
    deb: /tmp/docker-volume-netshare
  when: is_docker_volume_netshare|failed

- name: Start docker-volume-netshare on boot
  service:
    name: docker-volume-netshare
    enabled: yes
    state: started

- name: Modify grub to adjust memory and swap accounting
  lineinfile:
    dest: /etc/default/grub
    backup: yes
    regexp: GRUB_CMDLINE_LINUX=""$
    line: GRUB_CMDLINE_LINUX="cgroup_enable=memory swapaccount=1"
    backrefs: yes
    state: present
  register: result
  
- name: Reboot machine
  shell: sleep 2 && shutdown -r now "Ansible triggered reboot"
  async: 1
  poll: 0
  ignore_errors: true
  when: result.changed

- name: Wait for server boot
  local_action: wait_for host={{ inventory_hostname }} state=started delay=30 timeout=300 port=22
  when: result.changed  